# Configuração de desenvolvimento. O serviço fica em profile "turn" e NÃO é necessário
# para o primeiro teste em localhost.
listening-port=3478
fingerprint
lt-cred-mech
realm=local.webrtc
user=webrtc:troque-esta-senha
stale-nonce
no-cli
no-tls
no-dtls
no-multicast-peers
min-port=49160
max-port=49200
log-file=stdout
simple-log
